version: 2

jobs:
  test:
    docker:
      - image: continuumio/miniconda3

    steps:
      - checkout

      - run:
          name: install requirements
          command: conda install -y --file requirements.txt --channel conda-forge --channel bioconda

      - run:
          name: run cli help
          command: python rhoterm_caller.py -h
      - run:
          name: run test data
          command: (cd test && bash test.sh)

workflows:
  version: 2
  test:
    jobs:
      - test
